# -*- coding: utf-8 -*-
"""successful challenge 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZtiPUUDcBH5jcc71kn5rz7jRL7z7bX0
"""





"""# Challenge 4 — Imaging

The Chest X-Ray (CXR) is the most common image used in the NHS. In 2023/2024, the NHS reported 22 million CXRs requested and reported. Of these, 20% were normal , with a high margin of confidence. That's still 4 million CXRs that have utilised a precious human resource.

### Mission
Deploy and evaluate a pre-trained medical imaging AI for chest X-ray classification:
1. Load **TorchXRayVision** — a DenseNet-121 pre-trained on 100,000+ real clinical chest X-rays
2. Select the best pre-trained weight set for your task through structured evaluation
3. Map the model's 18 clinical outputs to your 4-class challenge task
4. Benchmark against the HuggingFace chest X-ray test set — report accuracy, sensitivity, and a confusion matrix
5. Visualise model reasoning using **GradCAM** (no fine-tuning required)
6. Combine with GPT-4o-mini to generate structured radiological reports
7. Add clinical guardrails and deploy as a live image upload app


### Why This Matters
Using AI to automate CXR review and report is a high-yield measure that can release clinicians to focus on high-touch (intervention) and high complexity ( second read cancer screening) tasks.

### Why No Fine-Tuning?
Cost!
But also:
Fine-tuning a general use pre-trained model from scratch on a small dataset is often **worse** than using a model already trained on a large, curated clinical dataset.

TorchXRayVision's DenseNet-121 was trained by researchers at Stanford, Montréal and MIT on:

| Dataset | Images | Source |
|---------|--------|--------|
| NIH ChestX-ray14 | 112,000 | US National Institutes of Health |
| CheXpert | 224,000 | Stanford University Medical Center |
| MIMIC-CXR | 370,000 | MIT / Beth Israel Deaconess Medical Center |
| PadChest | 160,000 | Hospital San Juan, Spain |
| RSNA Pneumonia | 30,000 | Radiological Society of North America |

Your task today is the job of a clinical AI team in the real world:
**select, evaluate, explain, and safely deploy a pre-trained model.**

> **Good news: No GPU required.** TorchXRayVision runs on CPU in seconds per image.
> You can use the standard Colab runtime.
"""

from google.colab import userdata
userdata.get('OPENAI_API_KEY')

from google.colab import userdata
import os, json
from openai import OpenAI

os.environ['OPENAI_API_KEY'] = userdata.get('OPENAI_API_KEY')
client = OpenAI()
print('OK OpenAI client ready.')



"""## Setup — API Key and OpenAI Client

## Step 1 — Install Libraries
"""

!pip install -q torchxrayvision scikit-image datasets Pillow scikit-learn

import torch
import torchxrayvision as xrv
import skimage
import torchvision
import torchvision.transforms as T
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from datasets import load_dataset
from collections import Counter
print('OK All libraries loaded.')
print(f'TorchXRayVision version: {xrv.__version__}')
print(f'PyTorch: {torch.__version__}')

"""## Step 2 — Load the Test Dataset

We use the same HuggingFace chest X-ray dataset as before, but this time we only need
the **test split** — there is nothing to train, so we go straight to evaluation.

In this task, we are evaluating the model on data it has **never seen**,
from a different source than its training data. This is called **out-of-distribution evaluation**
and it tells you far more about real-world clinical performance than validation accuracy ever can. We are also going to sample just the minimum number of images to deliver on the task (200).
"""

import random
from datasets import load_dataset
from collections import Counter

print('Loading chest X-ray test set from HuggingFace...')
# The original dataset 'keremberke/chest-xray-classification' is no longer supported by the 'datasets' library
# due to deprecated script loading. We are switching to a compatible dataset.
dataset = load_dataset('KVG-DataScience/chest_xray_dataset')

# We only need the test set for evaluation
test_ds_full = dataset['test']

# Stratified sampling: equal NORMAL and PNEUMONIA to avoid class-imbalance distortion
# Use up to 150 images per class (300 total) for a reliable AUC estimate
import random as _random
_random.seed(42)
_all_items = list(test_ds_full)
_label_names    = test_ds_full.features['label'].names  # e.g. ['NORMAL', 'PNEUMONIA']
_normal_idxs    = [i for i, x in enumerate(_all_items) if _label_names[x['label']] == 'NORMAL']
_pneumonia_idxs = [i for i, x in enumerate(_all_items) if _label_names[x['label']] == 'PNEUMONIA']
_n = min(len(_normal_idxs), len(_pneumonia_idxs), 100)  # 150 per class → 300 total
_sampled_idxs = _random.sample(_normal_idxs, _n) + _random.sample(_pneumonia_idxs, _n)
_random.shuffle(_sampled_idxs)
test_ds = test_ds_full.select(_sampled_idxs)
print(f'Stratified sample: {_n} NORMAL + {_n} PNEUMONIA = {len(test_ds)} total')

# The new dataset 'KVG-DataScience/chest_xray_dataset' has different labels:
# It typically has 'NORMAL' and 'PNEUMONIA' classes.
LABELS = test_ds.features['label'].names
print(f'Test images: {len(test_ds)}')
print(f'Classes: {LABELS}')

counts = Counter(test_ds['label'])
print('\nTest set distribution:')
for i, l in enumerate(LABELS):
    print(f'  {l:20s}: {counts.get(i,0):>4} images')

"""## Step 3 — Load TorchXRayVision Pre-Trained Model

TorchXRayVision offers several pre-trained weight sets. The key difference is **which
clinical dataset each model was trained on**, which directly affects which pathologies
it detects well and which populations it generalises to.

### Available Weight Sets
| Weights | Training Data | Best for |
|---------|---------------|----------|
| `densenet121-res224-all` | All datasets combined | Best overall generalisability |
| `densenet121-res224-rsna` | RSNA Pneumonia Challenge | Highest sensitivity for pneumonia |
| `densenet121-res224-nih` | NIH ChestX-ray14 (112k images) | Broad pathology coverage |
| `densenet121-res224-chex` | CheXpert (Stanford) | High-quality PA film performance |
| `densenet121-res224-mimic_nb` | MIMIC-CXR (MIT/BIDMC) | Large US hospital population |

We start with `densenet121-res224-all` (trained on all datasets) — the most robust choice
for an unknown test set. You can compare weight sets in Step 6.

## Step 4 — Map Model Outputs to the Challenge Classes

The TorchXRayVision model outputs 18 pathology scores. Our challenge has 4 classes.
We need to map between them.

This is a genuine clinical informatics task: real-world models rarely use exactly the
same label taxonomy as your evaluation dataset. Understanding how to bridge this gap —
and the uncertainty it introduces — is part of responsible AI deployment.

### Mapping Strategy
| Challenge Class | TorchXRayVision Output(s) Used |
|-----------------|-------------------------------|
| Pneumonia | `Pneumonia` + `Consolidation` (consolidation is the radiological correlate of pneumonia) |
| COVID-19 | `Consolidation` + `Infiltration` (COVID-19 was not in training data; see note below) |
| Pleural Effusion | `Effusion` |
| Normal | All pathology scores below threshold |

> **⚠️ COVID-19 note:** TorchXRayVision models were trained largely on pre-pandemic data.
> COVID-19 as a labelled class does not exist in the training data. The model may detect
> the radiological *features* of COVID-19 (bilateral consolidation, ground-glass opacity)
> without knowing the aetiological label. This is a real limitation and must be declared
> in your model card.
"""

WEIGHTS = 'densenet121-res224-chex'   # change this in Step 6 to compare models

print(f'Loading TorchXRayVision: {WEIGHTS}...')
model = xrv.models.DenseNet(weights=WEIGHTS)
model.eval()

print(f'OK Model loaded.')
print(f'Architecture:   DenseNet-121')
print(f'Input size:     224 × 224 (greyscale)')
print(f'Output:         {len(model.pathologies)} pathologies (sigmoid probabilities)')
print(f'\nAll pathologies the model can detect:')
for i, p in enumerate(model.pathologies):
    print(f'  {i+1:2d}. {p}')

# Map TorchXRayVision pathology indices to challenge classes
def get_pathology_idx(name):
    """Get index of a named pathology in the model's output vector."""
    return model.pathologies.index(name) if name in model.pathologies else None

PNEUMONIA_IDX  = get_pathology_idx('Pneumonia')
CONSOLID_IDX   = get_pathology_idx('Consolidation')
INFILTR_IDX    = get_pathology_idx('Infiltration')
EFFUSION_IDX   = get_pathology_idx('Effusion')

print('Pathology index mapping:')
print(f'  Pneumonia (index {PNEUMONIA_IDX})')
print(f'  Consolidation (index {CONSOLID_IDX})')
print(f'  Infiltration (index {INFILTR_IDX})')
print(f'  Effusion (index {EFFUSION_IDX})')

# Classification threshold — tune this in Step 5
THRESHOLD = 0.486  # sigmoid output above this = positive detection

def predict_challenge_class(probs, threshold=THRESHOLD):
    """Map 18-pathology sigmoid outputs to one of 'NORMAL' or 'PNEUMONIA' classes for binary challenge."""
    # Combine scores for pneumonia and consolidation, as these are the primary indicators for 'PNEUMONIA'
    # Weighted fusion: Pneumonia + Consolidation + Infiltration (all are radiological correlates)
    pneumonia_score = (
        0.5 * (probs[PNEUMONIA_IDX] if PNEUMONIA_IDX is not None else 0.0) +
        0.35 * (probs[CONSOLID_IDX] if CONSOLID_IDX is not None else 0.0) +
        0.15 * (probs[INFILTR_IDX]  if INFILTR_IDX  is not None else 0.0)
    )

    # For a binary classification task (NORMAL/PNEUMONIA)
    if pneumonia_score >= threshold:
        # If the combined pneumonia score is above the threshold, classify as PNEUMONIA
        return 'PNEUMONIA', pneumonia_score, {'PNEUMONIA': pneumonia_score, 'NORMAL': 1 - pneumonia_score}
    else:
        # Otherwise, classify as NORMAL
        return 'NORMAL', 1 - pneumonia_score, {'PNEUMONIA': pneumonia_score, 'NORMAL': 1 - pneumonia_score}

print('\nOK predict_challenge_class() ready.')
print(f'Detection threshold: {THRESHOLD}')

"""## Step 5 — Preprocess and Run Inference on Test Set

TorchXRayVision has its own preprocessing pipeline:
- Images must be **greyscale** (single channel)
- Pixel values must be **normalised to [-1024, 1024]** (DICOM range)
- Images are **centre-cropped and resized to 224×224**

This is intentionally different from standard ImageNet preprocessing — chest X-rays have
their own intensity distribution and preprocessing must respect the clinical image standard.
"""

# TorchXRayVision preprocessing pipeline
transform = T.Compose([
    xrv.datasets.XRayCenterCrop(),
    xrv.datasets.XRayResizer(224),
])

def preprocess_image(pil_img):
    """Convert PIL image to TorchXRayVision tensor."""
    img = np.array(pil_img.convert('L'))      # greyscale
    img = xrv.datasets.normalize(img, 255)     # [0,255] → [-1024,1024]
    img = img[None, ...]                        # add channel dim → (1, H, W)
    img = transform(img)                        # crop + resize
    return torch.from_numpy(img).unsqueeze(0)  # add batch dim → (1, 1, 224, 224)

# Run inference on entire test set
print('Running inference on test set...')


y_true, y_pred, all_probs = [], [], []

for i, sample in enumerate(test_ds):
    img_tensor = preprocess_image(sample['image'])
    with torch.no_grad():
        probs = torch.sigmoid(model(img_tensor))[0].numpy()  # 18-d probability vector
    pred_class, score, _ = predict_challenge_class(probs)
    y_true.append(LABELS[sample['label']])
    y_pred.append(pred_class)
    all_probs.append(probs)
    if (i+1) % 50 == 0:
        print(f'  {i+1}/{len(test_ds)} done...')

print(f'\nOK Inference complete on {len(test_ds)} images.')

"""## Step 6 — Evaluate: Accuracy, Sensitivity, Confusion Matrix

Now we assess performance against the ground-truth test labels.
The judges will score your model on a **10-image live test set** at demo time.
This full evaluation tells you what to expect.
"""

from sklearn.metrics import (classification_report, confusion_matrix,
                               ConfusionMatrixDisplay, accuracy_score)

# Overall accuracy
acc = accuracy_score(y_true, y_pred)
print(f'Overall Accuracy: {acc*100:.1f}%')

# Per-class report
print('\n--- Per-Class Report ---')
print(classification_report(y_true, y_pred, labels=LABELS, digits=3))

# Pneumonia sensitivity — the safety-critical metric
from sklearn.metrics import recall_score
pneumonia_recall = recall_score(
    [1 if y=='PNEUMONIA' else 0 for y in y_true],
    [1 if y=='PNEUMONIA' else 0 for y in y_pred]
)
print(f'⚠️  Pneumonia sensitivity: {pneumonia_recall*100:.1f}%  (judges weight this heavily)')
print(f'   A missed pneumonia = 0 pts for that image on demo day.')

# Confusion matrix
fig, ax = plt.subplots(figsize=(7, 6))
ConfusionMatrixDisplay.from_predictions(y_true, y_pred, labels=LABELS, ax=ax)
ax.set_title(f'Confusion Matrix — TorchXRayVision ({WEIGHTS})', fontsize=12)
plt.tight_layout()
plt.savefig('confusion_matrix.png', dpi=120)
plt.show()
print('Saved: confusion_matrix.png')

from sklearn.metrics import roc_auc_score, roc_curve, average_precision_score, PrecisionRecallDisplay
import numpy as np

# --- AUC & ROC ---
# Extract per-sample pneumonia probability using the same weighted fusion as predict_challenge_class()
pneumonia_probs = [
    0.5  * (p[PNEUMONIA_IDX] if PNEUMONIA_IDX is not None else 0.0) +
    0.35 * (p[CONSOLID_IDX] if CONSOLID_IDX is not None else 0.0)  +
    0.15 * (p[INFILTR_IDX] if INFILTR_IDX is not None else 0.0)
    for p in all_probs
]
y_binary = [1 if y == 'PNEUMONIA' else 0 for y in y_true]

auc = roc_auc_score(y_binary, pneumonia_probs)
print(f'\nROC-AUC: {auc:.4f}')

# Find optimal threshold via Youden's J (maximises sensitivity + specificity simultaneously)
fpr, tpr, thresholds = roc_curve(y_binary, pneumonia_probs)
optimal_idx       = np.argmax(tpr - fpr)
optimal_threshold = thresholds[optimal_idx]
print(f'Optimal threshold (Youden J): {optimal_threshold:.3f}')
print(f'  → Sensitivity at this threshold: {tpr[optimal_idx]*100:.1f}%')
print(f'  → Specificity at this threshold: {(1 - fpr[optimal_idx])*100:.1f}%')
print(f'  → Update THRESHOLD = {optimal_threshold:.3f} in Step 4 cell, then re-run Steps 4→5→6')

# ROC Curve plot
fig, ax = plt.subplots(figsize=(7, 6))
ax.plot(fpr, tpr, color='crimson', lw=2, label=f'ROC (AUC = {auc:.3f})')
ax.plot([0, 1], [0, 1], 'k--', lw=1, label='Random classifier')
ax.scatter(fpr[optimal_idx], tpr[optimal_idx], color='orange', zorder=5, s=80,
           label=f'Optimal threshold = {optimal_threshold:.2f}')
ax.set_xlabel('False Positive Rate (1 − Specificity)')
ax.set_ylabel('True Positive Rate (Sensitivity)')
ax.set_title(f'ROC Curve — {WEIGHTS}', fontsize=12)
ax.legend()
plt.tight_layout()
plt.savefig('roc_curve.png', dpi=120)
plt.show()
print('Saved: roc_curve.png')

# --- Precision-Recall Curve ---
pr_auc = average_precision_score(y_binary, pneumonia_probs)
print(f'\nPR-AUC (Average Precision): {pr_auc:.4f}')
fig2, ax2 = plt.subplots(figsize=(7, 6))
PrecisionRecallDisplay.from_predictions(y_binary, pneumonia_probs, ax=ax2)
ax2.set_title(f'Precision-Recall Curve — {WEIGHTS}', fontsize=12)
plt.tight_layout()
plt.savefig('pr_curve.png', dpi=120)
plt.show()
print('Saved: pr_curve.png')

"""## Step 6b — Model Comparison: Which Weight Set Performs Best?

This is the core learning task replacing fine-tuning. Rather than training your own model,
you are **selecting the best pre-trained model** for this specific clinical task.

Run the cell below to compare all available weight sets on the same test set.
This teaches a crucial real-world skill: **off-the-shelf models vary significantly in
performance depending on what clinical population they were trained on.**
"""

WEIGHT_SETS = [
    'densenet121-res224-all',
    'densenet121-res224-rsna',
    'densenet121-res224-nih',
    'densenet121-res224-chex',
    'densenet121-res224-mimic_nb',
]

results = {}
for w in WEIGHT_SETS:
    print(f'Testing {w}...')
    try:
        m = xrv.models.DenseNet(weights=w)
        m.eval()
        yt, yp = [], []
        for sample in test_ds:
            img_tensor = preprocess_image(sample['image'])
            with torch.no_grad():
                probs = torch.sigmoid(m(img_tensor))[0].numpy()
            # Re-index pathologies for this weight set
            # Note: Pathology indices might vary between different weight sets.
            # We need to get the indices dynamically for each model.
            model_pathologies = m.pathologies # Get pathologies for the current model

            p_idx = model_pathologies.index('Pneumonia') if 'Pneumonia' in model_pathologies else None
            c_idx = model_pathologies.index('Consolidation') if 'Consolidation' in model_pathologies else None
            e_idx = model_pathologies.index('Effusion') if 'Effusion' in model_pathologies else None
            i_idx = model_pathologies.index('Infiltration') if 'Infiltration' in model_pathologies else None

            # Recalculate pneumonia_score using current model's indices
            pneumonia_score = (
                0.5 * (probs[p_idx] if p_idx is not None else 0.0) +
                0.35 * (probs[c_idx] if c_idx is not None else 0.0) +
                0.15 * (probs[i_idx] if i_idx is not None else 0.0)
            )

            # For a binary classification task (NORMAL/PNEUMONIA)
            if pneumonia_score >= THRESHOLD:
                pred = 'PNEUMONIA'
            else:
                pred = 'NORMAL'

            yt.append(LABELS[sample['label']])
            yp.append(pred)

        acc = accuracy_score(yt, yp)
        pneu_recall = recall_score(
            [1 if y=='PNEUMONIA' else 0 for y in yt],
            [1 if y=='PNEUMONIA' else 0 for y in yp]
        )
        results[w] = {'accuracy': acc, 'pneumonia_sensitivity': pneu_recall}
        print(f'  Accuracy: {acc*100:.1f}%  |  Pneumonia sensitivity: {pneu_recall*100:.1f}%')
    except Exception as e:
        print(f'  Skipped {w}: {e}')
        results[w] = None

print('\n--- Summary ---')
print(f'{"Weights":<35} {"Accuracy":>10} {"Pneu. Recall":>14}')
print('-'*62)
for w, r in results.items():
    if r:
        print(f'{w:<35} {r["accuracy"]*100:>9.1f}% {r["pneumonia_sensitivity"]*100:>13.1f}%')

# Collect pneumonia probabilities from all models in WEIGHT_SETS
ensemble_pneumonia_probs = {w: [] for w in WEIGHT_SETS}

print('Collecting probabilities for ensemble from all weight sets...')

for w in WEIGHT_SETS:
    print(f'  Processing {w}...')
    try:
        model = xrv.models.DenseNet(weights=w)
        model.eval()

        # Dynamically get pathology indices for the current model
        model_pathologies = model.pathologies
        p_idx = model_pathologies.index('Pneumonia') if 'Pneumonia' in model_pathologies else None
        c_idx = model_pathologies.index('Consolidation') if 'Consolidation' in model_pathologies else None
        i_idx = model_pathologies.index('Infiltration') if 'Infiltration' in model_pathologies else None

        for sample in test_ds:
            img_tensor = preprocess_image(sample['image'])
            with torch.no_grad():
                probs = torch.sigmoid(model(img_tensor))[0].numpy()  # 18-d probability vector

            # Recalculate pneumonia_score using current model's indices
            pneumonia_score = (
                0.5 * (probs[p_idx] if p_idx is not None else 0.0) +
                0.35 * (probs[c_idx] if c_idx is not None else 0.0) +
                0.15 * (probs[i_idx] if i_idx is not None else 0.0)
            )
            ensemble_pneumonia_probs[w].append(pneumonia_score)

    except Exception as e:
        print(f'  Skipped {w} due to error: {e}')
        ensemble_pneumonia_probs[w] = [0.0] * len(test_ds) # Fill with zeros if model fails

print('\nOK. Collected probabilities for all models.')

# Define ensemble weights (can be tuned)
# For a start, we'll give slightly higher weight to the 'rsna' model as it had good sensitivity,
# and distribute the rest evenly. Total weights should sum to 1.
ensemble_weights = {
    'densenet121-res224-all': 0.2,
    'densenet121-res224-rsna': 0.3,
    'densenet121-res224-nih': 0.2,
    'densenet121-res224-chex': 0.15,
    'densenet121-res224-mimic_nb': 0.15,
}

# Ensure weights sum to 1 (simple normalization if they don't, or adjust manually)
weights_sum = sum(ensemble_weights.values())
if weights_sum != 1.0:
    ensemble_weights = {k: v / weights_sum for k, v in ensemble_weights.items()}

print('Ensemble weights:')
for w_name, weight in ensemble_weights.items():
    print(f'  {w_name}: {weight:.2f}')

# Calculate weighted average predictions
y_pred_ensemble = []

for i in range(len(test_ds)):
    weighted_avg_prob = 0.0
    for w_name, weight in ensemble_weights.items():
        if ensemble_pneumonia_probs[w_name]:
            weighted_avg_prob += ensemble_pneumonia_probs[w_name][i] * weight

    if weighted_avg_prob >= THRESHOLD:
        y_pred_ensemble.append('PNEUMONIA')
    else:
        y_pred_ensemble.append('NORMAL')

# Prepare y_true for evaluation
y_true_ensemble = [LABELS[sample['label']] for sample in test_ds]

print('\nOK. Ensemble predictions calculated.')

from sklearn.metrics import accuracy_score, recall_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Evaluate Ensemble performance
ensemble_acc = accuracy_score(y_true_ensemble, y_pred_ensemble)
ensemble_pneu_recall = recall_score(
    [1 if y=='PNEUMONIA' else 0 for y in y_true_ensemble],
    [1 if y=='PNEUMONIA' else 0 for y in y_pred_ensemble]
)

print(f'\n--- Ensemble Performance ---')
print(f'Overall Ensemble Accuracy: {ensemble_acc*100:.1f}%')
print(f'Ensemble Pneumonia Sensitivity: {ensemble_pneu_recall*100:.1f}%')

# Confusion matrix for the ensemble
fig, ax = plt.subplots(figsize=(7, 6))
ConfusionMatrixDisplay.from_predictions(y_true_ensemble, y_pred_ensemble, labels=LABELS, ax=ax)
ax.set_title(f'Ensemble Confusion Matrix (Threshold={THRESHOLD})', fontsize=12)
plt.tight_layout()
plt.savefig('ensemble_confusion_matrix.png', dpi=120)
plt.show()
print('Saved: ensemble_confusion_matrix.png')

print('\n*Note: You can adjust the `ensemble_weights` in the previous cell and re-run to experiment with different combinations. Also, the `THRESHOLD` (0.322) was optimized for a single model; re-optimizing it for the ensemble might yield further improvements.*')



"""## Step 7 — Generate Radiological Reports with GPT-4o-mini

The DenseNet classifies across 18 pathologies. GPT-4o-mini articulates those findings
as a structured consultant-radiologist report.

Unlike the fine-tuning approach, we now pass the **full 18-pathology probability vector**
to GPT-4o-mini — not just the top prediction. This gives the language model richer clinical
context and allows it to note secondary findings (e.g. "Effusion score is borderline at 0.28,
radiologist attention recommended").
"""

RADIOLOGY_SYS = """
You are a consultant radiologist assisting an AI-supported chest X-ray review workflow.


CONTEXT
- You will receive:
  1) a dictionary of 18 pathology probability scores (0.000-1.000) from a pre-trained TorchXRayVision DenseNet-121 model, and
  2) the top mapped challenge-class prediction with composite confidence.
- You are not directly viewing the image.
- These are model-output signals for decision support, not definitive radiological observations or final diagnoses.
- Your task is to convert the score pattern into a concise, clinician-readable structured report suitable for display in a radiology results card.


OUTPUT FORMAT
Return exactly one line in this exact format:
CHEST X-RAY REPORT | PRIMARY FINDING | SECONDARY FINDINGS | CLINICAL SIGNIFICANCE | URGENCY | RECOMMENDATION


CARD DISPLAY OPTIMIZATION
- Each section will be shown in its own row on a clinical report card.
- Write each section as a compact field entry, not as a long paragraph.
- Keep each field short, high-yield, and readable at a glance.
- Avoid repeating the same finding across multiple fields unless necessary for safety.
- Prefer noun-phrase or brief declarative style over lengthy prose.


SECTION RULES
1) CHEST X-RAY REPORT
- Provide a one-sentence overall summary of the model-supported radiographic pattern.
- If no strong abnormality is supported, say that no high-confidence acute cardiopulmonary abnormality is identified from the model outputs.

2) PRIMARY FINDING
- State the single most important supported abnormality.
- Use cautious language such as probable, possible, suspicious for, or no dominant abnormality identified.

3) SECONDARY FINDINGS
- Include only relevant secondary or borderline findings.
- Borderline scores from 0.20 to 0.40 should be described as borderline, indeterminate, or requiring attention.
- If none are relevant, say: No material secondary finding supported.

4) CLINICAL SIGNIFICANCE
- Briefly state why the pattern matters clinically.
- Focus on triage relevance, need for review, or whether the pattern is nonspecific/low confidence.
- Do not provide a definitive diagnosis.

5) URGENCY
- Output only one of:
  URGENT
  REVIEW REQUIRED
  ROUTINE
  NO IMMEDIATE AI-IDENTIFIED URGENT FINDING

6) RECOMMENDATION
- Give one brief, conservative next step.
- Appropriate language includes radiologist review, clinical correlation, and follow-up imaging if clinically indicated.
- Do not recommend treatment or disposition decisions.


INTERPRETATION RULES
- Prioritize the highest-probability clinically relevant thoracic findings.
- Treat Pneumonia and Consolidation as related air-space abnormality signals.
- Treat Effusion as a pleural abnormality signal.
- Do not overcall COVID-19; describe the radiographic pattern rather than asserting aetiology unless explicitly provided as the mapped class.
- Do not infer laterality, severity, chronicity, interval change, devices, or technical quality unless directly supported by the provided input.
- Do not mention low-probability incidental labels that would clutter the card.


SAFETY RULES
- Do not guess.
- Do not fabricate image details, measurements, history, comparisons, or symptoms.
- Do not say you can see the image.
- Do not provide a final diagnosis.
- If the pattern is weak, mixed, or uncertain, state that clearly and direct radiologist review.


STYLE TARGET
- Formal radiology tone.
- Concise and specific.
- Suitable for a consultant-facing demo card.
- No markdown, no bullets, no extra commentary, no extra delimiters.
"""

def classify_and_report(image_path_or_pil, title='Chest X-Ray', is_pediatric=False):
    """Full pipeline: preprocess → DenseNet inference → GPT-4o-mini report."""
    if isinstance(image_path_or_pil, str):
        pil_img = Image.open(image_path_or_pil)
    else:
        pil_img = image_path_or_pil

    img_tensor = preprocess_image(pil_img)
    with torch.no_grad():
        probs = torch.sigmoid(model(img_tensor))[0].numpy()

    # Full 18-pathology probability dict
    full_findings = {p: round(float(v), 3)
                     for p, v in zip(model.pathologies, probs)}

    # Challenge-class prediction
    pred_class, confidence, class_scores = predict_challenge_class(probs)

    # Apply guardrails to override prediction if necessary
    pred_class, alerts = apply_guardrails(pred_class, confidence, full_findings, is_pediatric=is_pediatric)

    # Build GPT prompt with full findings
    prompt = (
        f'18-pathology probability scores from DenseNet-121: {full_findings}\n'
        f'Top challenge-class prediction: {pred_class} '
        f'(composite confidence {confidence:.3f}).\n'
        'Generate a concise, cautious and structured radiology card report for clinician review.'
    )
    r = client.chat.completions.create(
        model='gpt-4o-mini',
        messages=[
            {'role': 'system', 'content': RADIOLOGY_SYS},
            {'role': 'user',   'content': prompt}
        ],
        temperature=0.1,
        max_tokens=300
    )
    report = r.choices[0].message.content
    return pred_class, confidence, full_findings, report, alerts

print('OK classify_and_report() ready.')

"""## Step 8 — XAI: Explain the Model with GradCAM

**Why does the model think it sees pneumonia?**

GradCAM (Gradient-weighted Class Activation Mapping) is the standard XAI method for CNN
architectures like DenseNet-121. It computes gradients flowing back from the predicted class
score into the final convolutional layer, then visualises which spatial regions activated most
strongly. This produces a heatmap overlaid on the original X-ray.

### Why GradCAM is Clinically Important
A model that correctly classifies "Pneumonia" but attends to the *left shoulder* instead of
the *right lower lobe* is not clinically trustworthy — it has learned a spurious correlation
(perhaps position of a medical device) rather than true pneumonic consolidation.

GradCAM lets a radiologist verify that the model is looking in the right place.

### XAI Method — for your Slide 2
| Method | Architecture | Output | Status |
|--------|-------------|--------|--------|
| **GradCAM** | DenseNet, ResNet, VGG (CNN) | Class activation heatmap | ✅ This notebook |
| Attention Rollout | Vision Transformer | Patch attention weights | For ViT architectures |
| LIME | Any | Superpixel attribution | Model-agnostic but slow |
| SHAP | Any | Pixel-level attribution | Computationally expensive |
"""

import torch.nn.functional as F
from PIL import Image

def gradcam(model, img_tensor, target_class_name):
    """
    Compute GradCAM heatmap for a target pathology class.
    Works with TorchXRayVision DenseNet-121.
    """
    target_idx = model.pathologies.index(target_class_name)
    gradients  = []
    activations= []

    # Hook: capture gradients at final convolutional layer
    def save_gradient(grad): gradients.append(grad)
    def save_activation(module, input, output):
        activations.append(output)
        output.register_hook(save_gradient)

    # Register hooks on final dense block
    handle = model.features.denseblock4.register_forward_hook(save_activation)

    # Forward pass
    output = torch.sigmoid(model(img_tensor))
    handle.remove()

    # Backward pass from target class
    model.zero_grad()
    output[0, target_idx].backward(retain_graph=True)

    # GradCAM computation
    pooled_grads = gradients[0].mean(dim=[0, 2, 3])       # global average pooling over spatial dims
    act = activations[0][0]                                 # (C, H, W)
    for i in range(act.shape[0]):
        act[i, :, :] *= pooled_grads[i]
    heatmap = act.mean(dim=0).detach().numpy()
    heatmap = np.maximum(heatmap, 0)                        # ReLU
    if heatmap.max() > 0:
        heatmap /= heatmap.max()                            # normalise to [0, 1]
    return heatmap

def display_gradcam(image_path_or_pil, target='Pneumonia'):
    """Classify, compute GradCAM, and display a 3-panel visualisation."""
    if isinstance(image_path_or_pil, str):
        pil_img = Image.open(image_path_or_pil).convert('L')
    else:
        pil_img = image_path_or_pil.convert('L')

    img_tensor = preprocess_image(pil_img)

    # Run GradCAM
    if target not in model.pathologies:
        print(f'Warning: {target} not in model pathologies. Using Pneumonia.')
        target = 'Pneumonia'
    heatmap = gradcam(model, img_tensor, target)

    # Upsample heatmap to original image size
    heatmap_resized = np.array(
        Image.fromarray((heatmap * 255).astype(np.uint8)).resize(pil_img.size, Image.BILINEAR)
    ) / 255.0

    fig, axes = plt.subplots(1, 3, figsize=(15, 5))
    orig = np.array(pil_img)

    axes[0].imshow(orig, cmap='gray'); axes[0].set_title('Original X-Ray'); axes[0].axis('off')
    axes[1].imshow(heatmap_resized, cmap='jet'); axes[1].set_title(f'GradCAM: {target}'); axes[1].axis('off')
    axes[2].imshow(orig, cmap='gray')
    axes[2].imshow(heatmap_resized, cmap='jet', alpha=0.45)
    axes[2].set_title('Overlay — What the model attended to'); axes[2].axis('off')

    plt.suptitle(f'XAI: GradCAM for {target} — DenseNet-121 ({WEIGHTS})',
                 fontsize=13, fontweight='bold')
    plt.tight_layout()
    plt.savefig('gradcam_output.png', dpi=120)
    plt.show()
    print('Saved: gradcam_output.png')
    print()
    print('A radiologist should verify the heatmap attends to:')
    print('  Pneumonia       → lower lobe consolidation / airspace opacity')
    print('  Effusion        → costophrenic angle / fluid meniscus')
    print('  Consolidation   → lobar or segmental opacity')
    print('  Normal          → no focal region should strongly dominate')

print('OK display_gradcam() ready.')
print('Usage: display_gradcam(pil_image, target="Pneumonia")')

"""## Step 9 — Clinical Guardrails

The model outputs 18 continuous probability scores — not hard binary decisions. A safe
clinical deployment must define explicit rules for when to escalate, when to flag
uncertainty, and when to refuse a "normal" verdict.

### Evidence Base
The following thresholds are grounded in:
- Rajpurkar et al. (2017) CheXNet: radiologist-level pneumonia detection requires recall ≥ 0.90
- NHS England AI imaging guidance: human-in-the-loop required for all AI-assisted reporting
- TorchXRayVision validation studies: `all`-weights model achieves AUC ~0.77–0.82 on external data
"""

PNEUMONIA_HARD_FLAG_THRESHOLD = 0.20   # any score above this → mandatory review
UNCERTAINTY_THRESHOLD         = 0.25   # composite confidence below this → uncertain
NORMAL_SAFETY_THRESHOLD       = 0.70   # Normal only returned if confidence ≥ this
NON_CXR_HEURISTIC_THRESHOLD   = 0.03   # Max pathology score below this suggests non-CXR or unrecognisable image

def apply_guardrails(pred_class, confidence, full_findings, is_pediatric=False):
    """Apply clinical safety rules to model output."""
    alerts = []

    # New Rule: Pediatric CXR
    if is_pediatric:
        alerts.insert(0, '🚨 CRITICAL ALERT — Pediatric patient identified. Model not trained on pediatric datasets; cannot provide reliable interpretation. Refer to paediatric radiologist.')
        return 'Pediatric CXR - Caution', alerts # Override predicted class

    # New Rule: Check if image is potentially not a CXR based on overall low pathology scores
    max_overall_prob = max(full_findings.values())
    if max_overall_prob < NON_CXR_HEURISTIC_THRESHOLD:
        alerts.insert(0, f'🚨 CRITICAL ALERT — Unrecognisable image pattern detected (max pathology score {max_overall_prob:.2f}). Referral back to emergency triage recommended.')
        return 'Not CXR / Unrecognisable', alerts # Override predicted class

    # Rule 1: Pneumonia hard flag (any above minimum threshold)
    pneu_raw = max(
        full_findings.get('Pneumonia', 0),
        full_findings.get('Consolidation', 0)
    )
    if pneu_raw >= PNEUMONIA_HARD_FLAG_THRESHOLD:
        alerts.append(f'⚠️  EXPEDITED REVIEW — Pneumonia/Consolidation score {pneu_raw:.2f} '
                      f'(threshold {PNEUMONIA_HARD_FLAG_THRESHOLD})')

    # Rule 2: Uncertainty flag
    if confidence < UNCERTAINTY_THRESHOLD:
        alerts.append(f'⚠️  UNCERTAIN — Max composite score {confidence:.2f} '
                      f'< {UNCERTAINTY_THRESHOLD} — Senior Radiologist Review Required')

    # Rule 3: Normal safety gate
    if pred_class == 'Normal' and confidence < NORMAL_SAFETY_THRESHOLD:
        pred_class = 'Indeterminate'
        alerts.append(f'⚠️  Normal withheld — confidence {confidence:.2f} '
                      f'< {NORMAL_SAFETY_THRESHOLD} safety threshold')

    # Rule 4: Secondary finding alert (borderline scores 0.20–0.40)
    borderline = [(p, v) for p, v in full_findings.items()
                  if 0.20 <= v <= 0.40 and p not in ['Pneumonia','Consolidation','Effusion','Infiltration']]
    if borderline:
        bl_str = ', '.join(f'{p} ({v:.2f})' for p, v in sorted(borderline, key=lambda x: -x[1])[:3])
        alerts.append(f'ℹ️  Borderline secondary findings: {bl_str}')

    return pred_class, alerts

print('OK Clinical guardrails defined.')
print(f'Pneumonia flag threshold:    ≥ {PNEUMONIA_HARD_FLAG_THRESHOLD}')
print(f'Uncertainty threshold:       < {UNCERTAINTY_THRESHOLD}')
print(f'Normal safety gate:          ≥ {NORMAL_SAFETY_THRESHOLD}')
print(f'Non-CXR heuristic threshold: < {NON_CXR_HEURISTIC_THRESHOLD}')

"""## Step 10 — Format the Report as a Clinical Card"""

from IPython.display import HTML, display

URGENCY_COLOURS = {
    'Normal':           ('#1a5c3a', '#e6f4eb'),
    'Pneumonia':        ('#8b1a1a', '#fce8e8'),
    'COVID-19':         ('#7a5200', '#fff3cd'),
    'Pleural Effusion': ('#003e74', '#e8eef5'),
    'Indeterminate':    ('#4e5d7a', '#f2ede4'),
    'Not CXR / Unrecognisable': ('#B00020', '#FFCDD2'), # New entry for unrecognisable images
    'Pediatric CXR - Caution': ('#FF5722', '#FFCCBC'), # Orange for caution for pediatric cases
}

def display_radiology_card(image_path_or_pil, title='Chest X-Ray Review', is_pediatric=False):
    """Full pipeline with formatted HTML output."""
    pred_class, confidence, full_findings, report, alerts = classify_and_report(image_path_or_pil, title, is_pediatric=is_pediatric)

    fg, bg = URGENCY_COLOURS.get(pred_class, ('#1a1a2e', '#f2ede4'))
    border  = '#8b1a1a' if alerts else fg

    alert_html = ''.join(
        f'<div style="background:#fce8e8;border-left:4px solid #8b1a1a;'
        f'padding:10px 14px;margin-bottom:8px;border-radius:0 4px 4px 0;'
        f'font-weight:700;color:#8b1a1a">{a}</div>'
        for a in alerts
    )

    sections = [s.strip() for s in report.split('|')]
    labels_  = ['Report','Primary Finding','Secondary Findings','Clinical Significance','Urgency','Recommendation']
    section_html = ''.join(
        f'<tr><td style="padding:8px 14px;font-weight:700;color:{fg};'
        f'white-space:nowrap;vertical-align:top;width:180px">'
        f'{labels_[i] if i < len(labels_) else ""}</td>'
        f'<td style="padding:8px 14px;color:#1a1a2e">{sec}</td></tr>'
        for i, sec in enumerate(sections)
    )

    # Top 6 pathology probability bars
    top6 = sorted(full_findings.items(), key=lambda x: -x[1])[:6]
    bars = ''.join(
        f'<div style="display:flex;align-items:center;gap:8px;margin-bottom:4px">'
        f'<span style="width:160px;font-size:12px;color:#4e5d7a">{p}</span>'
        f'<div style="flex:1;background:#e8eef5;border-radius:3px;height:14px">'
        f'<div style="width:{v*100:.1f}%;background:{fg};height:14px;border-radius:3px"></div></div>'
        f'<span style="width:40px;font-size:12px;font-weight:700;color:{fg}">{v*100:.1f}%</span>'
        f'</div>'
        for p, v in top6
    )

    html = f'''
    <div style="border:2px solid {border};border-radius:8px;overflow:hidden;
                font-family:'Segoe UI',Calibri,Arial,sans-serif;max-width:820px;margin:12px 0">
      <div style="background:#002147;padding:14px 20px;display:flex;
                  align-items:center;justify-content:space-between">
        <div>
          <div style="font-size:11px;letter-spacing:.14em;text-transform:uppercase;
                      color:#d4ae4a;margin-bottom:4px">
            Oxford Clinical AI · DenseNet-121 ({WEIGHTS})
          </div>
          <div style="font-size:18px;font-weight:700;color:#fff">{title}</div>
        </div>
        <div style="text-align:right">
          <div style="font-size:26px;font-weight:700;color:{fg};background:{bg};
                      padding:6px 16px;border-radius:4px">{pred_class}</div>
          <div style="font-size:12px;color:rgba(255,255,255,.55);margin-top:4px">
            Confidence {confidence*100:.1f}%
          </div>
        </div>
      </div>
      <div style="padding:14px 18px;background:#fff">
        {alert_html}
        <table style="width:100%;border-collapse:collapse;margin-bottom:14px">
          {section_html}
        </table>
        <div style="border-top:1px solid #d4d9e3;padding-top:12px">
          <div style="font-size:12px;font-weight:700;letter-spacing:.1em;text-transform:uppercase;
                      color:#4e5d7a;margin-bottom:8px">Top Pathology Scores</div>
          {bars}
        </div>
      </div>
      <div style="background:#f2ede4;padding:8px 18px;font-size:11px;color:#4e5d7a;
                  border-top:1px solid #d4d9e3">
        ⚕ For radiologist review only · Not for autonomous clinical decision-making ·
        TorchXRayVision DenseNet-121 · GPT-4o-mini · Oxford Clinical AI Hackathon 2026
      </div>
    </div>'''
    display(HTML(html))
    return pred_class, confidence, alerts

print('OK display_radiology_card() ready.')

"""##Example of a radiology report card"""

from google.colab import userdata
import os

# Fetch from Colab Secrets vault and expose as an environment variable.
# The OpenAI library picks it up automatically from os.environ.
try:
    os.environ['OPENAI_API_KEY'] = userdata.get('OPENAI_API_KEY')
    print('✅ API Key loaded from Colab Secrets.')
except Exception as e:
    print(f'🚨 Could not load key: {e}')
    print('   → Make sure OPENAI_API_KEY is added to Colab Secrets (🔑 icon)')
    print('   → and that the access toggle for this notebook is ON.')

# Save an example image from the test_ds to a temporary file
example_pil_img = test_ds[0]['image']
example_image_path = 'temp_cxr_example.png'
example_pil_img.save(example_image_path)

# Run inference using the image path
print(f"Running inference for image: {example_image_path}")
display_radiology_card(example_image_path, title='Test Inference from Image Path')

"""### Step 6c — Optimize Threshold for Weighted Average Ensemble"""

from sklearn.metrics import roc_auc_score, roc_curve, average_precision_score, PrecisionRecallDisplay
import numpy as np
import matplotlib.pyplot as plt

# We need the `weighted_avg_prob` from the ensemble calculation
# Re-calculate weighted average predictions (if not already in memory from previous run)
# Or, ensure `weighted_avg_prob` is available. For safety, let's regenerate it here.

ensemble_pneumonia_probs_list = []
for i in range(len(test_ds)):
    weighted_avg_prob = 0.0
    for w_name, weight in ensemble_weights.items():
        if ensemble_pneumonia_probs[w_name]:
            weighted_avg_prob += ensemble_pneumonia_probs[w_name][i] * weight
    ensemble_pneumonia_probs_list.append(weighted_avg_prob)

# Prepare y_true as binary (1 for PNEUMONIA, 0 for NORMAL)
y_binary_ensemble = [1 if y == 'PNEUMONIA' else 0 for y in y_true_ensemble]

# --- AUC & ROC ---
auc_ensemble = roc_auc_score(y_binary_ensemble, ensemble_pneumonia_probs_list)
print(f'\nEnsemble ROC-AUC: {auc_ensemble:.4f}')

# Find optimal threshold via Youden's J
fpr_ensemble, tpr_ensemble, thresholds_ensemble = roc_curve(y_binary_ensemble, ensemble_pneumonia_probs_list)
optimal_idx_ensemble       = np.argmax(tpr_ensemble - fpr_ensemble)
optimal_threshold_ensemble = thresholds_ensemble[optimal_idx_ensemble]
print(f'Optimal Ensemble threshold (Youden J): {optimal_threshold_ensemble:.3f}')
print(f'  → Sensitivity at this threshold: {tpr_ensemble[optimal_idx_ensemble]*100:.1f}%')
print(f'  → Specificity at this threshold: {(1 - fpr_ensemble[optimal_idx_ensemble])*100:.1f}%')
print(f'  → Update THRESHOLD = {optimal_threshold_ensemble:.3f} in Step 4 cell, then re-run Steps 4→5→6 to re-evaluate the ensemble with this new threshold.')

# ROC Curve plot
fig, ax = plt.subplots(figsize=(7, 6))
ax.plot(fpr_ensemble, tpr_ensemble, color='crimson', lw=2, label=f'ROC (AUC = {auc_ensemble:.3f})')
ax.plot([0, 1], [0, 1], 'k--', lw=1, label='Random classifier')
ax.scatter(fpr_ensemble[optimal_idx_ensemble], tpr_ensemble[optimal_idx_ensemble], color='orange', zorder=5, s=80,
           label=f'Optimal threshold = {optimal_threshold_ensemble:.2f}')
ax.set_xlabel('False Positive Rate (1 − Specificity)')
ax.set_ylabel('True Positive Rate (Sensitivity)')
ax.set_title(f'Ensemble ROC Curve', fontsize=12)
ax.legend()
plt.tight_layout()
plt.savefig('ensemble_roc_curve.png', dpi=120)
plt.show()
print('Saved: ensemble_roc_curve.png')

# --- Precision-Recall Curve ---
pr_auc_ensemble = average_precision_score(y_binary_ensemble, ensemble_pneumonia_probs_list)
print(f'\nEnsemble PR-AUC (Average Precision): {pr_auc_ensemble:.4f}')
fig2, ax2 = plt.subplots(figsize=(7, 6))
PrecisionRecallDisplay.from_predictions(y_binary_ensemble, ensemble_pneumonia_probs_list, ax=ax2)
ax2.set_title(f'Ensemble Precision-Recall Curve', fontsize=12)
plt.tight_layout()
plt.savefig('ensemble_pr_curve.png', dpi=120)
plt.show()
print('Saved: ensemble_pr_curve.png')

"""### Majority Voting Ensemble"""

# First, get binary predictions for each model based on their individual pneumonia probabilities
# We'll use the same THRESHOLD (0.322) for consistency for now.

model_binary_predictions = {w: [] for w in WEIGHT_SETS}

for w_name in WEIGHT_SETS:
    for prob in ensemble_pneumonia_probs[w_name]:
        if prob >= THRESHOLD:
            model_binary_predictions[w_name].append('PNEUMONIA')
        else:
            model_binary_predictions[w_name].append('NORMAL')

# Now, perform majority voting for each sample
y_pred_majority_vote = []

for i in range(len(test_ds)):
    pneumonia_votes = 0
    normal_votes = 0
    for w_name in WEIGHT_SETS:
        if model_binary_predictions[w_name][i] == 'PNEUMONIA':
            pneumonia_votes += 1
        else:
            normal_votes += 1

    if pneumonia_votes > normal_votes:
        y_pred_majority_vote.append('PNEUMONIA')
    elif normal_votes > pneumonia_votes:
        y_pred_majority_vote.append('NORMAL')
    else:
        # Tie-breaking: If votes are equal, default to 'NORMAL' for safety or require another rule.
        # For simplicity, we'll default to 'NORMAL' here.
        y_pred_majority_vote.append('NORMAL')

# Prepare y_true for evaluation (same as before)
y_true_majority_vote = [LABELS[sample['label']] for sample in test_ds]

print('OK. Majority vote ensemble predictions calculated.')

from sklearn.metrics import accuracy_score, recall_score, confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Evaluate Majority Voting Ensemble performance
majority_vote_acc = accuracy_score(y_true_majority_vote, y_pred_majority_vote)
majority_vote_pneu_recall = recall_score(
    [1 if y=='PNEUMONIA' else 0 for y in y_true_majority_vote],
    [1 if y=='PNEUMONIA' else 0 for y in y_pred_majority_vote]
)

print(f'\n--- Majority Voting Ensemble Performance ---')
print(f'Overall Majority Voting Ensemble Accuracy: {majority_vote_acc*100:.1f}%')
print(f'Majority Voting Ensemble Pneumonia Sensitivity: {majority_vote_pneu_recall*100:.1f}%')

# Confusion matrix for the majority voting ensemble
fig, ax = plt.subplots(figsize=(7, 6))
ConfusionMatrixDisplay.from_predictions(y_true_majority_vote, y_pred_majority_vote, labels=LABELS, ax=ax)
ax.set_title(f'Majority Voting Ensemble Confusion Matrix (Threshold={THRESHOLD})', fontsize=12)
plt.tight_layout()
plt.savefig('majority_vote_confusion_matrix.png', dpi=120)
plt.show()
print('Saved: majority_vote_confusion_matrix.png')

"""## Step 11 — Live Image Upload App (Demo Day Interface)"""

import ipywidgets as widgets
from IPython.display import display, clear_output

upload_btn  = widgets.FileUpload(accept='.jpg,.jpeg,.png', multiple=False,
                                  description='Upload CXR')
analyse_btn = widgets.Button(description='Analyse', button_style='primary',
                              icon='search', layout=widgets.Layout(width='140px',height='40px'))
gradcam_btn = widgets.Button(description='GradCAM', button_style='info',
                              icon='eye', layout=widgets.Layout(width='140px',height='40px'))
is_pediatric_checkbox = widgets.Checkbox(
    value=False,
    description='Pediatric Patient',
    disabled=False,
    indent=False
)
status      = widgets.Label('Upload a chest X-ray to begin.')
output_area = widgets.Output()
current_img = [None]

def on_analyse(b):
    with output_area:
        clear_output()
        if not upload_btn.value:
            status.value = 'Please upload an image first.'; return
        content = list(upload_btn.value.values())[0]['content']
        from io import BytesIO
        pil_img = Image.open(BytesIO(content)).convert('L')
        current_img[0] = pil_img
        status.value = 'Analysing...'
        try:
            # Pass the value from the checkbox to display_radiology_card
            pred, conf, alerts = display_radiology_card(pil_img, title='Live Demo Upload', is_pediatric=is_pediatric_checkbox.value)
            status.value = f'{pred} ({conf*100:.1f}%) — {"⚠️ Alerts raised" if alerts else "No alerts"}'
        except Exception as e:
            status.value = f'Error: {e}'

def on_gradcam(b):
    with output_area:
        if current_img[0] is None:
            status.value = 'Analyse an image first.'; return
        status.value = 'Computing GradCAM...'
        display_gradcam(current_img[0], target='Pneumonia')
        status.value = 'GradCAM complete.'

analyse_btn.on_click(on_analyse)
gradcam_btn.on_click(on_gradcam)

print('=== Oxford Clinical AI Hackathon, Challenge 4 — Chest X-Ray Classifier (TorchXRayVision) ===')
print ("Supported formats are .jpg, .jpg, .png")
display(widgets.VBox([
    widgets.HBox([upload_btn, analyse_btn, gradcam_btn, is_pediatric_checkbox]),
    status,
    output_area
]))

"""## Step 12 — Model Card (Domain 2: Explainability Slide)

Complete this for your demo day Slide 2. Every field will be probed.

### Architecture
| Field | Detail |
|-------|--------|
| Model | TorchXRayVision DenseNet-121 |
| Weights used | `densenet121-res224-rsna` (RSNA Pneumonia Challenge) |
| Architecture | DenseNet-121 with 121 dense layers and skip connections |
| Input | Greyscale X-ray, normalised to [-1024, 1024], resized 224×224 |
| Output | 18 pathology sigmoid scores (multi-label, not mutually exclusive) |
| Parameters | ~7 million |
| Inference speed | ~0.5s per image on CPU |

### Training Data (Data Provenance)
| Dataset | Images | Institution |
|---------|--------|-------------|
| NIH ChestX-ray14 | 112,000 | US National Institutes of Health |
| CheXpert | 224,000 | Stanford University Medical Center |
| MIMIC-CXR | 370,000 | MIT / Beth Israel Deaconess Medical Center |
| PadChest | 160,000 | Hospital San Juan, Spain |
| RSNA Pneumonia | 30,000 | Radiological Society of North America |

### Design Choices
| Choice | Rationale |
|--------|-----------|
| Pre-trained rather than fine-tuned | Model trained on 900k+ real clinical images outperforms a ViT fine-tuned on 1,000 images |
| `all`-weights | Best generalisation to unknown test distribution |
| Threshold 0.30 | Balances specificity and recall; lower increases sensitivity at cost of false positives |
| GradCAM over Attention Rollout | DenseNet is a CNN; GradCAM is the standard and most clinically interpretable method |

### Known Limitations *(Be honest — judges reward this)*
- COVID-19 is not a labelled class in training data; model detects radiological features, not the aetiology
- Trained predominantly on US and European hospitals; may underperform on images from other populations
- Not validated on mobile/AP X-rays; designed for PA (posteroanterior) films
- **Not validated on pediatric datasets; cannot provide reliable interpretation for pediatric patients.**
- GPT-4o-mini reports may generate plausible-sounding but inaccurate clinical statements
- Model outputs sigmoid probabilities, not clinical certainties; threshold selection is not validated

### XAI Method
**GradCAM** (Gradient-weighted Class Activation Mapping) — visualises which spatial regions of
the X-ray most strongly activate the class score of interest. Implemented on the final DenseNet
dense block. Radiologists should verify the heatmap corresponds to anatomically plausible findings.

## Step 13 — Governance Slide (Domain 3)

### 1. Acceptable Use
✅ **Appropriate contexts:**
- Preliminary pathology flagging to support radiologist triage
- Medical education and trainee self-assessment
- Research: feature extraction and baseline comparison for new CXR algorithms

🚫 **Explicitly excluded:**
- Autonomous reporting without radiologist oversight
- Paediatric patients (not trained or validated on paediatric films)
- Any setting where output is acted on without clinical review
- Use as primary diagnostic tool in emergency settings without human confirmation

### 2. Data Privacy
- Model weights are open source; no patient data required to run inference
- Uploaded X-rays are processed locally in Colab; no images are sent to external servers
- GPT-4o-mini receives only numeric probability scores — **no pixel data, no patient identifiers**
- Any NHS deployment must satisfy NHS DSPT, GDPR Article 9 (special category health data), and local IG policy

### 3. Monitoring Outputs
- Monthly radiologist audit: 20 random predictions reviewed against ground truth
- Automated quarterly re-evaluation against a fixed hold-out set; alert if AUC drops > 0.05
- User feedback mechanism: "Was this classification correct?" captured per report
- Retraining/update trigger: if pneumonia sensitivity falls below 0.80 in audit

### 4. Compliance with Existing Legislation
- **MHRA Software as a Medical Device (SaMD):** likely Class IIa or IIb; regulatory approval required before NHS clinical use
- **NHS AI Framework:** human oversight preserved; model is advisory only; clinician is decision-maker
- **Royal College of Radiologists AI guidance:** AI outputs must be presented as decision support, not diagnosis
- **UK GDPR Article 22:** automated decision-making with significant effects on persons requires human review

### 5. Ownership & Liability
- If a clinician acts on an incorrect AI prediction and patient harm results:
  current UK law places liability with **the clinician**, not the model developer or deploying institution
- Developer duty: ensure the system is deployed only within its validated clinical scope
- Escalation pathway: AI output contradicts clinical impression → second radiologist opinion required (not AI re-run)
- Indemnity: NHS trusts deploying AI tools must check their clinical negligence indemnity covers AI-assisted decisions

---

## Demo Day — Judging Criteria

Judges supply **10 live chest X-rays** not seen during evaluation. Your app must be running and ready.

### What the judges are assessing
> *"Does this AI communicate its findings in a way a clinician could act on? You are effectively reading a radiology report generated by a machine — apply the same standards you would to any radiology output."*
> — Judges' Briefing, Challenge 4

### Scoring Grid
| Domain | Criterion | Points |
|--------|-----------|--------|
| **Performance (Slide 1)** | Classification accuracy — 10 live images × 1 pt (pneumonia images scored first; missed pneumonia = 0 for that image) | **10** |
| **Performance (Slide 1)** | GPT radiology report quality — 5 judge-selected images × 1 pt (accurate finding + appropriate recommendation) | **5** |
| **Explainability (Slide 2)** | Model Card /2 · Data Provenance /1 · Known Limitations /1 · XAI Method proposed /1 | **5** |
| **Governance (Slide 3)** | Acceptable Use · Data Privacy · Monitoring · Compliance · Ownership & Liability (1 pt each) | **5** |
| **Total** | | **25** |

### XAI Judge Answer Key
The expected answer is **GradCAM** (or SHAP / LIME image variant).
Your Slide 2 must name the method, show a heatmap from at least one image, and explain
*why a radiologist would find it meaningful* — i.e. it reveals where the model looked, not just what it predicted.
"""